### ISSUE TITLE
NullPointerException on Yelp inference when run with -satisfaction

### ISSUE THREAD

**Issue by Modestas96** [linqs/psl-examples#16] opened 2021-06-28 15:23 UTC
Unexpected exception!
java.lang.NullPointerException
        at org.linqs.psl.cli.Launcher.outputGroundRules(Launcher.java:155)
        at org.linqs.psl.cli.Launcher.learnWeights(Launcher.java:290)
        at org.linqs.psl.cli.Launcher.run(Launcher.java:402)
        at org.linqs.psl.cli.Launcher.main(Launcher.java:466)
        at org.linqs.psl.cli.Launcher.main(Launcher.java:454)
ERROR: Failed to run weight learning

I get this error when running:
 ./run.sh -satisdaction

on Windows 10 and also on Windows 10 subsystem for Ubuntu.

I do not get this error while running simple-acquaintances for example

**Comment by eriq-augustine** [comment] 2021-06-28 15:48
Humm... I can't seem to reproduce this yet.

What branch of psl-examples are you using?
Were you running with `--satisfaction` or `-satisdaction`?

**Comment by Modestas96** [comment] 2021-06-28 15:54
Thank you for your quick response
Sorry for the mistype.
I ran ./run.sh -satisfaction groundings_sat.txt

I'm using the latest commit of the main branch: b45ed4ff25893de3e90a56c07f1c1c549ee1ea03

PSL version 2.2.1 (I tried newer versions as well, it did not seem to work).

**Comment by eriq-augustine** [comment] 2021-06-28 16:09
Thanks for the info, and for reporting the issue.

I found and fixed the issue:
https://github.com/linqs/psl/commit/00f02bb131bc7995d0933021b2c18af5e44a36d8

The fix is in the develop branch.
Will that work for you? (Are you okay with building your own version to get the fix?)
We plan on publishing a canary build soon and a full release by the end of the summer.

**Comment by Modestas96** [comment] 2021-06-28 16:32
Thanks a lot! 
I tried building from that branch unfortunately some tests from psl-cli have not passed when ran with mvn install. Can't wait for the new release.
Meanwhile, I would highly appreciate it, if you could upload the -satisfaction results somewhere, so I could continue my research.

or if you could send me an email: s2125517@ed.ac.uk

Thank you in advance!

**Comment by eriq-augustine** [comment] 2021-06-28 17:25
When building the develop branch, try skipping the tests using `-Dmaven.test.skip=true`. So something like:
```
mvn clean install -Dmaven.test.skip=true
```
Our CI already gave the green flag, so it should be fine to skip tests that may have trouble navigating Windows:
https://travis-ci.com/github/linqs/psl

**Comment by Modestas96** [comment] 2021-06-28 17:38
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for psl 2.3.0-SNAPSHOT:
[INFO]
[INFO] psl ................................................ SUCCESS [  0.907 s]
[INFO] psl-core ........................................... SUCCESS [ 15.412 s]
[INFO] psl-parser ......................................... SUCCESS [  5.932 s]
[INFO] psl-cli ............................................ SUCCESS [  5.502 s]
[INFO] psl-java ........................................... SUCCESS [  1.873 s]
[INFO] psl-python ......................................... FAILURE [  0.332 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.119 s
[INFO] Finished at: 2021-06-28T18:38:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (python-clean) on project psl-python: Command execution failed.: Cannot run program ".build\clean.sh" (in directory "C:\Users\jurci\Desktop\Master Thesis\PSL\psl-src\psl\psl-python"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :psl-python


Any advice here?

**Comment by eriq-augustine** [comment] 2021-06-28 18:00
Yeah, try skipping the psl-python submodule:
```
mvn -pl -psl-python clean install -Dmaven.test.skip=true
```

Sorry about the run-around here.
Because of the pandemic, I don't think we have any readily accessible
Windows machines.

Also, was this being run straight from Windows, or the WSL?
I think WSL should work (if the above doesn't already).

-eriq

**Comment by Modestas96** [comment] 2021-06-28 18:00
psl-python module failed to build. 
However after removing it from pom.xml build was successfully completed.
I do confirm that the -satisfaction option now work.

**Comment by eriq-augustine** [comment] 2021-06-28 18:02
Nice!
Glad to hear your got everything working.

**Closed as completed by eriq-augustine** 2021-06-28 18:02 UTC
